name: CI/CD

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "k8s/**"

permissions:
  contents: write

env:
  IMAGE_NAME: flask-app

jobs:
  build_push_update_manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./dockerfile
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update deployment image tag to SHA
        run: |
          sed -i "s/:VERSION/:${{ github.sha }}/" k8s/deployment.yaml
          cat k8s/deployment.yaml

      - name: Update deployment image tag to SHA
        shell: bash
        run: |
          FILE="k8s/deployment.yaml"
          sed -i -E "s|(image:\s*docker\.io/[^ ]+):.*|\1:${{ github.sha }}|" "$FILE"
          echo "Updated manifest:"
          cat "$FILE"